<?php


$projects = [
    ['date' => '2025', 'version' => 'v4', 'title' => 'CV'],
    ['date' => '2025', 'version' => 'v1', 'title' => 'Template 2'],
    ['date' => '2025', 'version' => 'v1', 'title' => 'Git archive'],
    ['date' => '2024', 'version' => 'v1', 'title' => 'Brocante 50'],
    ['date' => '2024', 'version' => 'v1', 'title' => 'Alarm'],
    ['date' => '2024', 'version' => 'v1', 'title' => 'Animation<br>svg/three.js/webgl 2d'],
    ['date' => '2024', 'version' => 'v1', 'title' => 'Job Scrapper'],
    ['date' => '2024', 'version' => 'v1', 'title' => 'Job Lister'],
    ['date' => '2024', 'version' => 'v1', 'title' => 'Docker Starter', 'data_text' => 'better detection of docker desktop running + better hide windows'],
    ['date' => '2024', 'version' => 'v1', 'title' => 'Dump Organizer', 'data_text' => 'use local'],
    ['date' => '2024', 'version' => 'v1', 'title' => 'Github Init', 'data_text' => 'adjust adding htdocs folder navigation'],
    ['date' => '2020', 'version' => 'v1', 'title' => 'Websocket Chat'],
    ['date' => '2019', 'version' => 'v1', 'title' => 'Barnabe AperoVan'],
    ['date' => '2018', 'version' => 'v1', 'title' => 'ACBC Consulting'],
    ['date' => '2018', 'version' => 'v1', 'title' => 'HTML Small Template'],
    ['date' => '2017', 'version' => 'v1', 'title' => 'Calculatrice PWA'],
    ['date' => '2017', 'version' => 'v1', 'title' => 'Tool Sublime Text<br>diff history'],
    ['date' => '2017', 'version' => 'v1', 'title' => 'Fast Order Images'],
    ['date' => '2017', 'version' => 'v1', 'title' => 'Nombre romain', 'data_text' => 'première apporche node.js'],
    ['date' => '2017', 'version' => 'v1', 'title' => 'YT Watcher'],
    ['date' => '2016', 'version' => 'prototype', 'title' => 'Wysiwyg Basique'],
    ['date' => '2016', 'version' => 'prototype', 'title' => 'Bam collectif<br>Rouen'],
    ['date' => '2016', 'version' => 'v1', 'title' => 'Bam collectif<br>La Courneuve'],
    ['date' => '2016', 'version' => 'v1', 'title' => 'Filemaker api basic'],
    ['date' => '2015', 'version' => 'v1', 'title' => 'Bam collectif<br>Factory API Gandi'],
    ['date' => '2015', 'version' => 'v1', 'title' => 'Bam collectif<br>Saint-Jean de Braye'],
    ['date' => '2014', 'version' => 'v3', 'title' => 'CV'],
    ['date' => '2014', 'version' => 'v1', 'title' => 'Bam collectif<br>Trouville-sur-Mer'],
    ['date' => '2012', 'version' => 'v1', 'title' => 'Cress archiveur<br>Assistance à la déduplication de fichiers'],
    ['date' => '2012', 'version' => 'v2', 'title' => 'CV'],
    ['date' => '2012', 'version' => 'v2', 'title' => 'Modula'],
    ['date' => '2012', 'version' => 'v1', 'title' => 'Modula'],
    ['date' => '2011', 'version' => 'v1 - vb.net', 'title' => 'Simple Backup Files'],
    ['date' => '2011', 'version' => 'v1 - vb.net', 'title' => 'Filmothèque'],
    ['date' => '2011', 'version' => 'v1 - vb.net', 'title' => 'Compta', 'download' => 'files/projet/compta.zip'],
    ['date' => '2010', 'version' => 'v1', 'title' => 'Image Crop'],
    ['date' => '2010', 'version' => 'v1', 'title' => "Verson'Optique"],
    ['date' => '2009', 'version' => 'v1', 'title' => 'Arborescence'],
    ['date' => '2009', 'version' => 'v1', 'title' => 'CV'],
    ['date' => '2009', 'version' => 'v1', 'title' => 'Emmanuel Touzé'],
    ['date' => '2006-2008', 'version' => 'v1', 'title' => 'Divers module JS/PHP<br>intégré dans des CMS<br>(Nuked-klan, webSPELL)'],
    ['date' => '2006-2008', 'version' => 'v1', 'title' => 'Recrutement équipe counter-strike'],
    ['date' => '?/2004', 'version' => 'v1', 'title' => 'Damn simple cms'],
];

?>