<?php

$ytChannels = [
    [
        'date' => '2007-2020',
        'nbrVideos' => 5187,
        'img' => 'images/culture/yt/Google_Developers.jpg',
        'img_alt' => 'logo de Google Developers',
        'title' => 'Google Developers',
        'url' => 'https://www.youtube.com/Google%20Developers/videos',
    ],
    [
        'date' => '2013-2019',
        'nbrVideos' => 124,
        'img' => 'images/culture/yt/inUseExp.jpg',
        'img_alt' => 'logo de inUseExp',
        'title' => 'inUseExp',
        'url' => 'https://www.youtube.com/inUseExp/videos',
    ],
    [
        'date' => '2007-2020',
        'nbrVideos' => 2326,
        'img' => 'images/culture/yt/Google.jpg',
        'img_alt' => 'logo de Google',
        'title' => 'Google',
        'url' => 'https://www.youtube.com/Google/videos',
    ],
    [
        'date' => '2012-2020',
        'nbrVideos' => 1068,
        'img' => 'images/culture/yt/Google_Chrome_Developers.jpg',
        'img_alt' => 'logo de Google Chrome Developers',
        'title' => 'Google Chrome Developers',
        'url' => 'https://www.youtube.com/Google%20Chrome%20Developers/videos',
    ],
    [
        'date' => '2016-2020',
        'nbrVideos' => 479,
        'img' => 'images/culture/yt/Firebase.jpg',
        'img_alt' => 'logo de Firebase',
        'title' => 'Firebase',
        'url' => 'https://www.youtube.com/Firebase/videos',
    ],
    [
        'date' => '2008-2020',
        'nbrVideos' => 6556,
        'img' => 'images/culture/yt/OReilly.jpg',
        'img_alt' => 'logo de O\'Reilly',
        'title' => 'O\'Reilly',
        'url' => 'https://www.youtube.com/@oreilly/videos',
    ],
    [
        'date' => '2013-2014',
        'nbrVideos' => 36,
        'img' => 'images/culture/yt/AtmosphereConference.jpg',
        'img_alt' => 'logo de AtmosphereConference',
        'title' => 'AtmosphereConference',
        'url' => 'https://www.youtube.com/AtmosphereConference/videos',
    ],
    [
        'date' => '2012-2020',
        'nbrVideos' => 1589,
        'img' => 'images/culture/yt/JSConf.jpg',
        'img_alt' => 'logo de JSConf',
        'title' => 'JSConf',
        'url' => 'https://www.youtube.com/@jsconf_/videos',
    ],
    [
        'date' => '2013-2020',
        'nbrVideos' => 607,
        'img' => 'images/culture/yt/Facebook_Developers.jpg',
        'img_alt' => 'logo de Facebook Developers',
        'title' => 'Facebook Developers',
        'url' => 'https://www.youtube.com/Facebook%20Developers/videos',
    ],
    [
        'date' => '2013-2019',
        'nbrVideos' => 342,
        'img' => 'images/culture/yt/DevTips.jpg',
        'img_alt' => 'logo de DevTips',
        'title' => 'DevTips',
        'url' => 'https://www.youtube.com/@OfficialDevTips/videos',
    ],
    [
        'date' => '2016-2020',
        'nbrVideos' => 3131,
        'img' => 'images/culture/yt/CNCF_Cloud_Native_Computing_Foundation.jpg',
        'img_alt' => 'logo de DevTips',
        'title' => 'CNCF [Cloud Native Computing Foundation]',
        'url' => 'https://www.youtube.com/@cncf/videos',
    ],
    [
        'date' => '2010-2020',
        'nbrVideos' => 1108,
        'img' => 'images/culture/yt/JetBrainsTV.jpg',
        'img_alt' => 'logo de JetBrainsTV',
        'title' => 'JetBrainsTV',
        'url' => 'https://www.youtube.com/JetBrainsTV/videos',
    ],
    [
        'date' => '2014-2019',
        'nbrVideos' => 22,
        'img' => 'images/culture/yt/Google_Developers_Launchpad.jpg',
        'img_alt' => 'logo de Google Developers Launchpad',
        'title' => 'Google Developers Launchpad',
        'url' => 'https://www.youtube.com/Google%20Developers%20Launchpad/videos',
    ],
    [
        'date' => '2016-2019',
        'nbrVideos' => 48,
        'img' => 'images/culture/yt/ThoughtWorks_Products.jpg',
        'img_alt' => 'logo de ThoughtWorks Products',
        'title' => 'ThoughtWorks Products',
        'url' => 'https://www.youtube.com/@thoughtworksproducts8308/videos',
    ],
    [
        'date' => '2011-2020',
        'nbrVideos' => 1278,
        'img' => 'images/culture/yt/GOTO_Conferences.jpg',
        'img_alt' => 'logo de GOTO Conferences',
        'title' => 'GOTO Conferences',
        'url' => 'https://www.youtube.com/GOTO%20Conferences/videos',
    ],
    [
        'date' => '2011-2014',
        'nbrVideos' => 309,
        'img' => 'images/culture/yt/YUI_Library.jpg',
        'img_alt' => 'logo de YUI Library',
        'title' => 'YUI Library',
        'url' => 'https://www.youtube.com/YUI%20Library/videos',
    ],
    [
        'date' => '2015-2018',
        'nbrVideos' => 56,
        'img' => 'images/culture/yt/ColdFront.jpg',
        'img_alt' => 'logo de ColdFront',
        'title' => 'ColdFront',
        'url' => 'https://www.youtube.com/@coldfront8363/videos',
    ],
    [
        'date' => '2018-2020',
        'nbrVideos' => 202,
        'img' => 'images/culture/yt/Google_Developer_Groups.jpg',
        'img_alt' => 'logo de Google Developer Groups',
        'title' => 'Google Developer Groups',
        'url' => 'https://www.youtube.com/@GoogleDeveloperGroups/videos',
    ],
    [
        'date' => '2017-2020',
        'nbrVideos' => 194,
        'img' => 'images/culture/yt/The_AMP_Channel.jpg',
        'img_alt' => 'logo de The AMP Channel',
        'title' => 'The AMP Channel',
        'url' => 'https://www.youtube.com/@TheAMPProject/videos',
    ],
    [
        'date' => '2009-2020',
        'nbrVideos' => 1225,
        'img' => 'images/culture/yt/Codecourse.jpg',
        'img_alt' => 'logo de Codecourse',
        'title' => 'Codecourse',
        'url' => 'https://www.youtube.com/Codecourse/videos',
    ],
    [
        'date' => '2014-2020',
        'nbrVideos' => 2618,
        'img' => 'images/culture/yt/Google_Cloud_Platform.jpg',
        'img_alt' => 'logo de Google Cloud Platform',
        'title' => 'Google Cloud Platform',
        'url' => 'https://www.youtube.com/Google%20Cloud%20Platform/videos',
    ],
    [
        'date' => '2018-2020',
        'nbrVideos' => 316,
        'img' => 'images/culture/yt/TensorFlow.jpg',
        'img_alt' => 'logo de TensorFlow',
        'title' => 'TensorFlow',
        'url' => 'https://www.youtube.com/TensorFlow/videos',
    ],
    [
        'date' => '2014-2019',
        'nbrVideos' => 204,
        'img' => 'images/culture/yt/Codegram_Technologies.jpg',
        'img_alt' => 'logo de Codegram Technologies',
        'title' => 'Codegram Technologies',
        'url' => 'https://www.youtube.com/@Codegram/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 208,
        'img' => 'images/culture/yt/Made_by_Google.jpg',
        'img_alt' => 'logo de Made by Google',
        'title' => 'Made by Google',
        'url' => 'https://www.youtube.com/Made%20by%20Google/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 268,
        'img' => 'images/culture/yt/Fun_Fun_Function.jpg',
        'img_alt' => 'logo de Fun Fun Function',
        'title' => 'Fun Fun Function',
        'url' => 'https://www.youtube.com/Fun%20Fun%20Function/videos',
    ],
    [
        'date' => '2006-2020',
        'nbrVideos' => 226,
        'img' => 'images/culture/yt/Wes_Bos.jpg',
        'img_alt' => 'logo de Wes Bos',
        'title' => 'Wes Bos',
        'url' => 'https://www.youtube.com/Wes%20Bos/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 1269,
        'img' => 'images/culture/yt/The_Net_Ninja.jpg',
        'img_alt' => 'logo de The Net Ninja',
        'title' => 'The Net Ninja',
        'url' => 'https://www.youtube.com/The%20Net%20Ninja/videos',
    ],
    [
        'date' => '2013-2020',
        'nbrVideos' => 509,
        'img' => 'images/culture/yt/dotconferences.jpg',
        'img_alt' => 'logo de dotconferences',
        'title' => 'dotconferences',
        'url' => 'https://www.youtube.com/dotconferences/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 179,
        'img' => 'images/culture/yt/Google_Design.jpg',
        'img_alt' => 'logo de Google Design',
        'title' => 'Google Design',
        'url' => 'https://www.youtube.com/Google%20Design/videos',
    ],
    [
        'date' => '2012-2012',
        'nbrVideos' => 511,
        'img' => 'images/culture/yt/GoogleTalksArchive.jpg',
        'img_alt' => 'logo de GoogleTalksArchive',
        'title' => 'GoogleTalksArchive',
        'url' => 'https://www.youtube.com/GoogleTalksArchive/videos',
    ],
    [
        'date' => '2008-2014',
        'nbrVideos' => 143,
        'img' => 'images/culture/yt/webdirections.jpg',
        'img_alt' => 'logo de webdirections',
        'title' => 'webdirections',
        'url' => 'https://www.youtube.com/webdirections/videos',
    ],
    [
        'date' => '2011-2020',
        'nbrVideos' => 4504,
        'img' => 'images/culture/yt/Confreaks.jpg',
        'img_alt' => 'logo de Confreaks',
        'title' => 'Confreaks',
        'url' => 'https://www.youtube.com/Confreaks/videos',
    ],
    [
        'date' => '2014-2016',
        'nbrVideos' => 146,
        'img' => 'images/culture/yt/Nodevember.jpg',
        'img_alt' => 'logo de Nodevember',
        'title' => 'Nodevember',
        'url' => 'https://www.youtube.com/Nodevember/videos',
    ],
    [
        'date' => '2017-2019',
        'nbrVideos' => 17,
        'img' => 'images/culture/yt/ZEIT.jpg',
        'img_alt' => 'logo de ZEIT',
        'title' => 'ZEIT',
        'url' => 'https://www.youtube.com/@VercelHQ/videos',
    ],
    [
        'date' => '2013-2017',
        'nbrVideos' => 95,
        'img' => 'images/culture/yt/Twitter_University.jpg',
        'img_alt' => 'logo de Twitter University',
        'title' => 'Twitter University',
        'url' => 'https://www.youtube.com/Twitter%20University/videos',
    ],
    [
        'date' => '2012-2020',
        'nbrVideos' => 1146,
        'img' => 'images/culture/yt/LevelUpTuts.jpg',
        'img_alt' => 'logo de LevelUpTuts',
        'title' => 'LevelUpTuts',
        'url' => 'https://www.youtube.com/LevelUpTuts/videos',
    ],
    [
        'date' => '2016-2019',
        'nbrVideos' => 23,
        'img' => 'images/culture/yt/Codexpanse.jpg',
        'img_alt' => 'logo de Codexpanse',
        'title' => 'Codexpanse',
        'url' => 'https://www.youtube.com/Codexpanse/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 99,
        'img' => 'images/culture/yt/Women_Techmakers.jpg',
        'img_alt' => 'logo de Women Techmakers',
        'title' => 'Women Techmakers',
        'url' => 'https://www.youtube.com/Women%20Techmakers/videos',
    ],
    [
        'date' => '2014-2019',
        'nbrVideos' => 147,
        'img' => 'images/culture/yt/Twitter_Dev.jpg',
        'img_alt' => 'logo de Twitter Dev',
        'title' => 'Twitter Dev',
        'url' => 'https://www.youtube.com/Twitter%20Dev/videos',
    ],
    [
        'date' => '2014-2018',
        'nbrVideos' => 24,
        'img' => 'images/culture/yt/Dialogflow.jpg',
        'img_alt' => 'logo de Dialogflow',
        'title' => 'Dialogflow',
        'url' => 'n\'existe plus',
    ],
    [
        'date' => '2013-2015',
        'nbrVideos' => 108,
        'img' => 'images/culture/yt/jquery.jpg',
        'img_alt' => 'logo de jquery',
        'title' => 'jquery',
        'url' => 'https://www.youtube.com/jquery/videos',
    ],
    [
        'date' => '2016-2020',
        'nbrVideos' => 102,
        'img' => 'images/culture/yt/Serverless.jpg',
        'img_alt' => 'logo de Serverless',
        'title' => 'Serverless',
        'url' => 'https://www.youtube.com/Serverless/videos',
    ],
    [
        'date' => '2018-2020',
        'nbrVideos' => 80,
        'img' => 'images/culture/yt/An_Event_Apart.jpg',
        'img_alt' => 'logo de An Event Apart',
        'title' => 'An Event Apart',
        'url' => 'https://www.youtube.com/@AnEventApartLive/videos',
    ],
    [
        'date' => '2013-2018',
        'nbrVideos' => 145,
        'img' => 'images/culture/yt/EmpireJS.jpg',
        'img_alt' => 'logo de EmpireJS',
        'title' => 'EmpireJS',
        'url' => 'https://www.youtube.com/EmpireJS/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 1280,
        'img' => 'images/culture/yt/nodejs.jpg',
        'img_alt' => 'logo de node.js',
        'title' => 'node.js',
        'url' => 'https://www.youtube.com/@nodejs-foundation/videos',
    ],
    [
        'date' => '2015-2016',
        'nbrVideos' => 46,
        'img' => 'images/culture/yt/JavaScript_Air.jpg',
        'img_alt' => 'logo de JavaScript Air',
        'title' => 'JavaScript Air',
        'url' => 'https://www.youtube.com/JavaScript%20Air/videos',
    ],
    [
        'date' => '2013-2018',
        'nbrVideos' => 98,
        'img' => 'images/culture/yt/Frontend_Conference_Zurich.jpg',
        'img_alt' => 'logo de Frontend Conference Zurich',
        'title' => 'Frontend Conference Zurich',
        'url' => 'https://www.youtube.com/@FrontZurich/videos',
    ],
    [
        'date' => '2007-2020',
        'nbrVideos' => 2086,
        'img' => 'images/culture/yt/GoogleTechTalks.jpg',
        'img_alt' => 'logo de GoogleTechTalks',
        'title' => 'GoogleTechTalks',
        'url' => 'https://www.youtube.com/GoogleTechTalks/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 228,
        'img' => 'images/culture/yt/Foo_Bar.jpg',
        'img_alt' => 'logo de Foo Bar',
        'title' => 'Foo Bar',
        'url' => 'https://www.youtube.com/@foobar_codes/videos',
    ],
    [
        'date' => '2009-2017',
        'nbrVideos' => 4700,
        'img' => 'images/culture/yt/OReilly__Video_Training.jpg',
        'img_alt' => 'logo de O\'Reilly - Video Training',
        'title' => 'O\'Reilly - Video Training',
        'url' => 'https://www.youtube.com/@oreillymediavideo/videos',
    ],
    [
        'date' => '2008-2020',
        'nbrVideos' => 1583,
        'img' => 'images/culture/yt/G_Suite.jpg',
        'img_alt' => 'logo de G Suite',
        'title' => 'G Suite',
        'url' => 'https://www.youtube.com/@googleworkspace/videos',
    ],
    [
        'date' => '2018-2018',
        'nbrVideos' => 32,
        'img' => 'images/culture/yt/Layout_Land.jpg',
        'img_alt' => 'logo de Layout Land',
        'title' => 'Layout Land',
        'url' => 'https://www.youtube.com/Layout%20Land/videos',
    ],
    [
        'date' => '2011-2020',
        'nbrVideos' => 1080,
        'img' => 'images/culture/yt/InfoQ.jpg',
        'img_alt' => 'logo de InfoQ',
        'title' => 'InfoQ',
        'url' => 'https://www.youtube.com/InfoQ/videos',
    ],
    [
        'date' => '2018-2020',
        'nbrVideos' => 688,
        'img' => 'images/culture/yt/Google_Cloud.jpg',
        'img_alt' => 'logo de Google Cloud',
        'title' => 'Google Cloud',
        'url' => 'https://www.youtube.com/Google%20Cloud/videos',
    ],
    [
        'date' => '2013-2020',
        'nbrVideos' => 162,
        'img' => 'images/culture/yt/LearnCodeacademy.jpg',
        'img_alt' => 'logo de LearnCode.academy',
        'title' => 'LearnCode.academy',
        'url' => 'https://www.youtube.com/@learncodeacademy/videos',
    ],
    [
        'date' => '2009-2020',
        'nbrVideos' => 1421,
        'img' => 'images/culture/yt/Google_Webmasters.jpg',
        'img_alt' => 'logo de Google Webmasters',
        'title' => 'Google Webmasters',
        'url' => 'https://www.youtube.com/@GoogleSearchCentral/videos',
    ],
    [
        'date' => '2016-2020',
        'nbrVideos' => 154,
        'img' => 'images/culture/yt/jsla.jpg',
        'img_alt' => 'logo de js.la',
        'title' => 'js.la',
        'url' => 'https://www.youtube.com/@JSlaArchives/videos',
    ],
    [
        'date' => '2009-2020',
        'nbrVideos' => 472,
        'img' => 'images/culture/yt/apigee.jpg',
        'img_alt' => 'logo de apigee',
        'title' => 'apigee',
        'url' => 'https://www.youtube.com/apigee/videos',
    ],
    [
        'date' => '2009-2020',
        'nbrVideos' => 427,
        'img' => 'images/culture/yt/Mozilla_Hacks.jpg',
        'img_alt' => 'logo de Mozilla Hacks',
        'title' => 'Mozilla Hacks',
        'url' => 'https://www.youtube.com/@mozhacks/videos',
    ],
    [
        'date' => '2010-2017',
        'nbrVideos' => 43,
        'img' => 'images/culture/yt/Paul_Irish.jpg',
        'img_alt' => 'logo de Paul Irish',
        'title' => 'Paul Irish',
        'url' => 'https://www.youtube.com/Paul%20Irish/videos',
    ],
    [
        'date' => '2011-2020',
        'nbrVideos' => 272,
        'img' => 'images/culture/yt/Chris_Coyier.jpg',
        'img_alt' => 'logo de Chris Coyier',
        'title' => 'Chris Coyier',
        'url' => 'https://www.youtube.com/@realcsstricks/videos',
    ],
    [
        'date' => '2017-2020',
        'nbrVideos' => 768,
        'img' => 'images/culture/yt/Coding_Tech.jpg',
        'img_alt' => 'logo de Coding Tech',
        'title' => 'Coding Tech',
        'url' => 'https://www.youtube.com/Coding%20Tech/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 1100,
        'img' => 'images/culture/yt/freeCodeCamporg.jpg',
        'img_alt' => 'logo de freeCodeCamp.org',
        'title' => 'freeCodeCamp.org',
        'url' => 'https://www.youtube.com/@freecodecamp/videos',
    ],
    [
        'date' => '2015-2020',
        'nbrVideos' => 584,
        'img' => 'images/culture/yt/Academind.jpg',
        'img_alt' => 'logo de Academind',
        'title' => 'Academind',
        'url' => 'https://www.youtube.com/Academind/videos',
    ],
    [
        'date' => '2012-2020',
        'nbrVideos' => 125,
        'img' => 'images/culture/yt/MySQL.jpg',
        'img_alt' => 'logo de MySQL',
        'title' => 'MySQL',
        'url' => 'https://www.youtube.com/MySQL/videos',
    ],
    [
        'date' => '2012-2020',
        'nbrVideos' => 381,
        'img' => 'images/culture/yt/Quentin_Watt_Tutorials.jpg',
        'img_alt' => 'logo de Quentin Watt Tutorials',
        'title' => 'Quentin Watt Tutorials',
        'url' => 'https://www.youtube.com/@QuentinWatt/videos',
    ],
    [
        'date' => '2019-2019',
        'nbrVideos' => 30,
        'img' => 'images/culture/yt/Mozilla_Developer.jpg',
        'img_alt' => 'logo de Mozilla Developer',
        'title' => 'Mozilla Developer',
        'url' => 'https://www.youtube.com/Mozilla%20Developer/videos',
    ],
    [
        'date' => '2018-2019',
        'nbrVideos' => 26,
        'img' => 'images/culture/yt/Paul_Lewis.jpg',
        'img_alt' => 'logo de Paul Lewis',
        'title' => 'Paul Lewis',
        'url' => 'https://www.youtube.com/@aerotwist/videos',
    ],
];

?>